Fixed garbled characters in NON ASCII Code
jenkinsci/google-chat-notification-plugin pull request #20
Opened 2019-10-16 10:32 UTC by yshingai

Use jackson for JSON encoding

2019-10-21 12:19 UTC, chiragnaik commented
@yshingai Please fix the build issue

2023-03-28 18:51 UTC, chiragnaik approved these changes

2023-04-01 22:20 UTC, Ryudo302 commented on src/main/java/io/cnaik/service/CommonUtil.java
> +            }
@yshingai Please add exception handling here (maybe just log?)

2023-04-01 22:22 UTC, Ryudo302 requested changes

2023-04-01 22:22 UTC, Ryudo302 commented on src/main/java/io/cnaik/service/CommonUtil.java
> +            } catch (Exception e) {
Please add exception handling here (maybe just log?)

2023-04-01 22:22 UTC, Ryudo302 commented on src/main/java/io/cnaik/service/CommonUtil.java
> +            class Response {
@yshingai I suggest you to create a new file for this class. Probably in the package `io.cnaik.model.google`.

2023-09-18 02:01 UTC, closed without merging